### ISSUE TITLE
Add a Known Issues page

### ISSUE THREAD

**Issue by Swader** [phalcon/website#117]
Add highly visible known issues page to the website, separated by version. Something like
## 1.3.0.

no known issues
## 1.2.1.

Asset Manager sometimes generates empty file.
Asset Manager adds semicolons between files.
## 1.2.0.

Asset Manager sometimes generates empty file.
Asset Manager adds semicolons between files.

Etc.

If issue is opened for given bug, it should be linked to the entry on the page.

**Comment by niden** [comment]
Moved to new repo - possibly set this up in the docs?
