### ISSUE TITLE
The Swedish website is showing the flag of El Salvador

### ISSUE THREAD

**Issue by indiebytes** [phalcon/website#344]
**Steps to reproduce:**
1. Go to https://phalconphp.com/
2. Select Swedish in the language dropdown in the top navigation

... or...
1. Go to https://phalconphp.com/sv/

**Expected result:**
1. The flag icon shows the Swedish flag to visualise the selected language

**Actual result:**
1. The flag icon shows the flag of El Salvador, see screenshot below

![sv-se](https://cloud.githubusercontent.com/assets/91565/18742666/d579f3e4-80b5-11e6-8c00-baacfb537938.png)

**Comment by indiebytes** [comment]
It's basically a quite simple mixup where the Swedish language code `sv` is being used as country code, the Swedish country code is `se` though. We should associate a country code to the language for the loading of correct flag.

While doing this we could also associate a hreflang value so [hreflang tags](https://moz.com/learn/seo/hreflang-tag) can be implemented for improved SERP listings. This should perhaps get it's own issue though.

**Comment by indiebytes** [comment]
@sergeyklay I'll get back with a pull request as soon as possible.

**Comment by niden** [comment]
Fixed with https://github.com/phalcon/website/pull/364
