### ISSUE TITLE
RuntimeException::__toString() 

### ISSUE THREAD

**Issue by wflashy** [phalcon/website#360]
Warning: RuntimeException::__toString() must return a string in Unknown on line 0 Fatal error: Uncaught thrown in /var/app/var/bootstrap.php on line 68 

use phalcon3.0.3

**Comment by sergeyklay** [comment]
Cc: @niden

**Comment by niden** [comment]
@wflashy Can you please check again and let us know where this happened? We have deployed a new version today so if there are any glitches we would love to hear about them so that we can fix them

**Comment by niden** [comment]
Closing - no reply
