### ISSUE TITLE
New Implementation - Redo translations

### ISSUE THREAD

**Issue by niden** [phalcon/website#361]
The structure of the application as is now does not reflect a "good" sample for a tutorial. In addition a lot of the translations are not working or are not in transifex which makes the website non translatable.

- [x] Rework the structure/bootstrap of the website to showcase a Phalcon implementation
- [x] Add all the strings in the translation file so that contributors can translate it
- [x] Remove non supported languages that crept in
- [x] Update content with links to store/patreon
- [ ] Tests

**Comment by niden** [comment]
Deployed

**Comment by sergeyklay** [comment]
👍
