### ISSUE TITLE
Older versions download links are broken

### ISSUE THREAD

**Issue by aunhappy** [phalcon/website#379]
When I download Phalcon 2.0.13 - Windows x64 for PHP 5.6 (vc11) on https://phalconphp.com/en/download/windows .the url redirect to https://phalconphp.com/en/download/windows#. I can't download file. :( All older versions download links are broken.Also ,I need phalcon for PHP 5.3 and 5.4,where I can find the older versions?

**Comment by niden** [comment]
@aunhappy thanks for reporting this. It has now been corrected - download links for the previous major version work.

As for 5.3/5.4 PHP, we have stopped supporting those versions. You can however get those DLLs if you browse the repository. For instance browsing this commit in time will give you the 5.4 DLLs

https://github.com/phalcon/website/tree/804735fbe978f1ad0b058857f6c6ab0cfe7478b5/public/files

The files are under `public/files`
