### ISSUE TITLE
Repository size

### ISSUE THREAD

**Issue by evolic** [phalcon/website#403]
Hi there,

I have just cloned this repository and just couldn't believe that it took 941.97 MiB.
How can it be possible for such small project?

--
Very best,
Tomasz Kuter

**Comment by sergeyklay** [comment]
You just cloned all binaries :)

Cc: @niden

**Comment by niden** [comment]
The binaries are in the history sadly. We used to store all the DLLs in the project and after the latest redesign we actually did the right thing and took them out.

I will see if I can remove them from the repo

**Comment by sergeyklay** [comment]
Is this issue still relevant?

**Comment by ninjapanzer** [comment]
If we don't need the binaries in the history I am happy to do a branch filter and reduce the size of the repo.

**Comment by ninjapanzer** [comment]
I will not remove the files because this will rewrite the history but I have extracted the existing binaries for archiving and will truncate the existing files

**Comment by ninjapanzer** [comment]
When we verify we aren't going to break crowdin run
```bash
bfg --delete-files phalcon_*.zip --protect-blobs-from master .
git push -f master origin/master
# do some associated rebasing on other open branches
```

When everything is fine delete branch `backup_master_with_binaries` from github
this will move the filesize of the project to 97mb

**Comment by niden** [comment]
Resolved - archiving this project
