### ISSUE TITLE
Incorrect Flags to Language association

### ISSUE THREAD

**Issue by Ultimater** [phalcon/website#416]
For example Arabic (using this as an example because it's first on the list alphabetically) is using the Argentina flag as the current logic assumes "ar" for Arabic has its own flag. This logic is causing a bunch of the flags not to even show any flag at all. Even if these associations were correct, many people would find the flags being associated to their language offensive as there's many countries which speak a certain language. For example if we tried to assign a flag for Arabic, which flag do we choose? Saudi Arabia? Palestine? Egypt? Morocco? Lebanon?  Jordan? Syria? Yemen? Another issue is even if we chose a specific flag, the countries tend to speak multiple languages, not specifically only Arabic. This issue extends beyond Arabic. I believe, the best solution would be to omit flags altogether, and use the language name (e.g. English) instead of a flag (e.g. USA).

As there's multiple files affected by the flag logic, it's not an easy fix that I can toss in a PR for this right now, but will work on one later when I have enough free time to see this change through.

![flags](https://cloud.githubusercontent.com/assets/1922199/26605773/27695688-4544-11e7-9b46-cba1eb1b7b3d.png)

**Comment by andresgutierrez** [comment]
+1

**Comment by Ultimater** [comment]
Alternatively we could use the flag associations crowdin is using:
https://crowdin.com/project/demo

**Comment by ninjapanzer** [comment]
I am calling the crowdin api for link.phalcon I can bring that deploy task here.

**Comment by niden** [comment]
Resolved in the new site
