### ISSUE TITLE
Phalcon homepage has rendered php at the bottom left of the page

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/website#469]
_From @troglodyte on December 22, 2017 13:25_

slate('about') ?> 

^-- is rendered on the bottom left.
https://phalconphp.com/en/

Not sure where else to put this bug...

> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

> Provide output if related. Provide coredump if any. Use https://github.com/phalcon/cphalcon/wiki/Generating-a-backtrace as reference

```php
// paste output here
```
> Provide minimal script to reproduce the issue

```php
// paste code
```
### Details

* Phalcon version: (`php --ri phalcon`)
* PHP Version: (`php -v`)
* Operating System:
* Installation type: Compiling from source || installing via package manager
* Zephir version (if any):
* Server: Nginx | Apache | Other
* Other related info (Database, table schema): 

_Copied from original issue: phalcon/cphalcon#13231_

**Comment by sergeyklay** [comment]
_From @Jurigag on December 22, 2017 14:4_

This PR is for issues with phalcon. For website use https://github.com/phalcon/website

**Comment by sergeyklay** [comment]
_From @JABirchall on December 25, 2017 13:54_

This issue is encountered on this view https://github.com/phalcon/website/blob/96567a1d644e15dc6e16a2a5784a3856efc0a7b0/app/views/include/footer.volt#L31

However this looks normal, So it maybe an issue with Phalcon::Volt 3.3 if that is what the website is running.

**Comment by niden** [comment]
This has been fixed; It was bad cache from CloudFlare/Site
