### ISSUE TITLE
Main page language item is incorrect #13545  Open

### ISSUE THREAD

**Issue by jimmyadaro** [phalcon/website#488]
I've seen this errors in the /es/ version of the main project page.

![47298404-11101700-d5ee-11e8-9532-a3d81948ae35](https://user-images.githubusercontent.com/20187699/47305297-66a0ef80-d5ff-11e8-9975-d3bdc74eda08.png)

1. The arabic language flag is actually the Argentina flag
2. The catalan language flag is actually the Canada flag
3. The language selector is positioned down in the menu (at least in my MBP 2011 13" 1280x800 display)

**Comment by mmilanovic4** [comment]
There is also wrong mapping for Serbian language (**Српски**) - you need to change class from `flag-sr` to `flag-rs`. Also, flag for Czech language is wrong. I suggest you to check all the others as well.

**Comment by niden** [comment]
Resolved
