### ISSUE TITLE
BASE_PATH in documentation may be inaccurate

### ISSUE THREAD

**Issue by dvohra** [phalcon/website#503]
The BASE_PATH in Phalcon tutorial https://docs.phalconphp.com/en/3.4/tutorial-base is inaccurate.

`define('BASE_PATH', dirname(__DIR__));`

Based on directory structure used with `index.php` in public dir `BASE_PATH` should be 
`define('BASE_PATH', dirname(__DIR__ . '/..'));`

**Comment by niden** [comment]
@dvohra Could you be so kind as to open this issue in the `docs` repository since it relates to that? We can then check it and address it.

Thank you

**Comment by dvohra** [comment]
Thanks added https://github.com/phalcon/docs/issues/2047
